#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Fix broken FAQ sections in wordcasefix HTML files.
Each faq-item currently has single chars; replaces with full 5-Q&A sections."""

import os, re

SITE_DIR = r"C:\Users\Administrator\wordcasefix"
MARKER = "<!-- seo-expanded -->"
SKIP = {"404.html", "about.html", "privacy-policy.html"}

def get_cat(slug):
    if re.search(r'color|gradient|hex.to.rgb|rgb.to|palette|contrast|color.picker|color.conv|color.mix', slug):
        return 'color'
    if re.search(r'json|xml|yaml|csv|html.enc|html.strip|html.to|css.min|css.beau|css.flex|css.unit|css.anim|javascript|regex|base64|binary|hex|ascii|chmod|cron|jwt|htaccess|http.status|ip.address|epoch|url.enc|url.dec|markdown', slug):
        return 'dev'
    if re.search(r'generator|barcode|qr.code|lorem|password|roman|upside|wingdings|morse|invisible|fancy|bubble|bold|italic|cursive|flip.text|fullwidth|small.caps|strikethrough|handwriting|text.repeat', slug):
        return 'gen'
    if re.search(r'calculator|bmi|calorie|gpa|grade|tip.calc|percentage|fraction|inflation|fuel.cost|electricity|break.even|compound|hourly|word.to.pages|aspect.ratio|average|discount|body.fat|carbon', slug):
        return 'calc'
    if re.search(r'date|countdown|days.between|age.calc|epoch.conv', slug):
        return 'time'
    if re.search(r'currency|unit.conv|celsius|fahrenheit|font.size.conv|css.unit', slug):
        return 'convert'
    return 'text'

def get_tool_name(content, slug):
    m = re.search(r'<h1[^>]*>([^<]+)</h1>', content)
    if m:
        return m.group(1).strip()
    m = re.search(r'<title>([^<|]+)', content)
    if m:
        t = m.group(1).strip()
        if ' - ' in t:
            return t.split(' - ')[0].strip()
        if ' | ' in t:
            return t.split(' | ')[0].strip()
        return t
    return slug.replace('-', ' ').title()

def build_faq(name, cat):
    templates = {
        'color': [
            ("Is {} free to use?".format(name),
             "Yes, completely free. {} requires no account, no subscription, and no payment. Use it as many times as you need at no cost.".format(name)),
            ("What color formats does {} support?".format(name),
             "{} supports the most common web and design color formats including HEX, RGB, HSL, and CMYK, with instant conversion between supported formats.".format(name)),
            ("Can I use the {} output directly in CSS?".format(name),
             "Yes. {} is optimized for web development workflows. Copy the converted value directly into your CSS, HTML, Sass, or any other web-related code.".format(name)),
            ("Does {} work on mobile devices?".format(name),
             "Yes. {} is fully responsive and works on smartphones, tablets, and desktop browsers without any installation required.".format(name)),
            ("Is my data sent to any server when I use {}?".format(name),
             "No. All processing in {} happens locally in your browser using JavaScript. No data is transmitted to or stored on any server.".format(name)),
        ],
        'dev': [
            ("Is {} free to use?".format(name),
             "Yes, completely free. {} is available with no signup required, no subscription, and no usage limits whatsoever.".format(name)),
            ("Does {} work offline after the page loads?".format(name),
             "Once the page is loaded, {} processes all data locally in your browser. An active connection is only needed for the initial page load.".format(name)),
            ("Is my data safe when using {}?".format(name),
             "Yes. All processing in {} happens client-side in your browser. Your code or input data is never sent to or stored on any server.".format(name)),
            ("Can I use {} for production work?".format(name),
             "Yes. {} uses reliable, tested algorithms suitable for professional use. Always verify critical outputs independently for production-critical systems.".format(name)),
            ("What browsers does {} support?".format(name),
             "{} works in all modern browsers including Chrome, Firefox, Safari, Edge, and Opera on both desktop and mobile devices.".format(name)),
        ],
        'gen': [
            ("Is {} free to use?".format(name),
             "Yes, completely free. {} requires no account, no subscription, and has no usage limits.".format(name)),
            ("Can I copy the output from {}?".format(name),
             "Yes. {} includes a one-click copy button so you can instantly paste the generated content into any application.".format(name)),
            ("Where can I use content generated by {}?".format(name),
             "Content from {} can be used in social media profiles, design mockups, presentations, documents, messaging apps, or any other application.".format(name)),
            ("Does {} work on mobile devices?".format(name),
             "Yes. {} is fully responsive and works on smartphones and tablets as well as desktop browsers without any installation.".format(name)),
            ("Is content generated by {} stored anywhere?".format(name),
             "No. {} generates all content locally in your browser. Nothing is sent to or stored on any server.".format(name)),
        ],
        'calc': [
            ("Is {} free to use?".format(name),
             "Yes, completely free. {} requires no account, no download, and no payment of any kind.".format(name)),
            ("How accurate is {}?".format(name),
             "{} uses verified formulas and delivers results to the appropriate number of decimal places, giving you reliable and accurate outputs every time.".format(name)),
            ("Can I use {} on my smartphone?".format(name),
             "Yes. {} is mobile-friendly and works on any modern smartphone or tablet browser without installation.".format(name)),
            ("Do I need to create an account to use {}?".format(name),
             "No. {} is available immediately with no registration, no login, and no personal information required.".format(name)),
            ("Are my inputs saved anywhere when I use {}?".format(name),
             "No. {} processes all calculations locally in your browser. No data is sent to or stored on any server.".format(name)),
        ],
        'time': [
            ("Is {} free to use?".format(name),
             "Yes, completely free. {} is available with no signup required, no subscription, and no usage limits.".format(name)),
            ("How accurate is {}?".format(name),
             "{} accounts for edge cases including leap years and time zone offsets to deliver precise, reliable results every time.".format(name)),
            ("Does {} handle leap years correctly?".format(name),
             "Yes. {} automatically accounts for leap years and other calendar edge cases in all date and time calculations.".format(name)),
            ("Can I use {} on my mobile device?".format(name),
             "Yes. {} is fully responsive and works on smartphones and tablets without any app installation required.".format(name)),
            ("Is my data sent to any server when I use {}?".format(name),
             "No. All calculations in {} are performed locally in your browser. No data is transmitted to any server.".format(name)),
        ],
        'convert': [
            ("Is {} free to use?".format(name),
             "Yes, completely free. {} requires no account, no subscription, and has no usage limits.".format(name)),
            ("How accurate are conversions in {}?".format(name),
             "{} uses accurate, up-to-date conversion factors. The conversion formula is displayed so you can verify the calculation if needed.".format(name)),
            ("Can I use {} on my mobile device?".format(name),
             "Yes. {} is fully responsive and works on smartphones and tablets as well as desktop browsers.".format(name)),
            ("Do I need to install anything to use {}?".format(name),
             "No installation is needed. {} runs entirely in your browser with no apps, plugins, or extensions required.".format(name)),
            ("Is any data stored when I use {}?".format(name),
             "No. All conversions in {} are performed locally in your browser. No data is sent to or stored on any server.".format(name)),
        ],
        'text': [
            ("Is {} free to use?".format(name),
             "Yes, completely free. {} requires no account, no subscription, and no payment. Use it as often as you like with no limits.".format(name)),
            ("Is there a character or word limit in {}?".format(name),
             "No. {} handles text of any length. Paste in as much content as you need and the tool processes it all instantly.".format(name)),
            ("Does {} work in my browser without installation?".format(name),
             "Yes. {} runs entirely in your browser using client-side JavaScript. No software, extension, or plugin installation is required.".format(name)),
            ("Is my text kept private when I use {}?".format(name),
             "Yes. All text processing in {} happens locally in your browser. Your text is never sent to or stored on any server.".format(name)),
            ("Can I use {} on a mobile device?".format(name),
             "Yes. {} is fully responsive and works on smartphones and tablets as well as desktop computers.".format(name)),
        ],
    }
    pairs = templates.get(cat, templates['text'])
    items = []
    for q, a in pairs:
        items.append(
            '  <div class="faq-item">\n'
            '    <h3>{}</h3>\n'
            '    <p>{}</p>\n'
            '  </div>'.format(q, a)
        )
    return (
        '<section class="faq-section">\n'
        '  <h2>Frequently Asked Questions</h2>\n'
        + '\n'.join(items) +
        '\n</section>'
    )

def fix_file(filepath):
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()

    if MARKER not in content:
        return False, "no_marker"

    start = content.find('<section class="faq-section">')
    if start == -1:
        return False, "no_faq"

    # Depth-track to find matching </section>
    pos = start + 1
    depth = 1
    end = -1
    while pos < len(content) and depth > 0:
        open_pos = content.find('<section', pos)
        close_pos = content.find('</section>', pos)
        if close_pos == -1:
            break
        if open_pos != -1 and open_pos < close_pos:
            depth += 1
            pos = open_pos + 1
        else:
            depth -= 1
            if depth == 0:
                end = close_pos + len('</section>')
            pos = close_pos + 1

    if end == -1:
        return False, "no_close"

    slug = os.path.basename(filepath).replace('.html', '')
    cat = get_cat(slug)
    name = get_tool_name(content, slug)
    new_faq = build_faq(name, cat)

    new_content = content[:start] + new_faq + content[end:]

    with open(filepath, 'w', encoding='utf-8', newline='') as f:
        f.write(new_content)

    return True, cat

def main():
    files = sorted([f for f in os.listdir(SITE_DIR)
                    if f.endswith('.html') and f not in SKIP])
    fixed = skipped = errors = 0
    for fname in files:
        fpath = os.path.join(SITE_DIR, fname)
        ok, msg = fix_file(fpath)
        if ok:
            fixed += 1
            print("  OK  {} ({})".format(fname.replace('.html',''), msg))
        elif msg == "no_marker":
            skipped += 1
        else:
            errors += 1
            print("  !!  {} ({})".format(fname.replace('.html',''), msg))
    print("\nDone: fixed={}, skipped_no_marker={}, errors={}".format(fixed, skipped, errors))

if __name__ == '__main__':
    main()
